/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fetch_entity/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch Entity */
        get: operations["fetch_entity_v1_fetch_entity__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fetch_source/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch Source */
        get: operations["fetch_source_v1_fetch_source__episode_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose */
        post: operations["propose_v1_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proposal */
        get: operations["get_proposal_v1_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/importers/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Types
         * @description All importer types the registry knows about.
         */
        get: operations["list_types_admin_importers_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/importers/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover Route
         * @description Probe the source with provided creds and list available items.
         *
         *     No DB writes — secrets stay in memory only. The wizard sends them
         *     again on save (where they get encrypted).
         */
        post: operations["discover_route_admin_importers_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/importers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Route */
        get: operations["list_route_admin_importers__get"];
        put?: never;
        /** Create Route */
        post: operations["create_route_admin_importers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/importers/{importer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route */
        get: operations["get_route_admin_importers__importer_id__get"];
        put?: never;
        post?: never;
        /** Delete Route */
        delete: operations["delete_route_admin_importers__importer_id__delete"];
        options?: never;
        head?: never;
        /** Update Route */
        patch: operations["update_route_admin_importers__importer_id__patch"];
        trace?: never;
    };
    "/admin/importers/{importer_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Route
         * @description Kick off a run in the background. Returns immediately with the
         *     importer id; poll `/{id}/runs` for the actual run row's progress.
         *
         *     We instantiate the importer up-front (without running it) so a
         *     missing optional-dep package fails the request with a 422 +
         *     pip-install hint instead of letting the background task swallow
         *     the error into the run row.
         */
        post: operations["run_route_admin_importers__importer_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/importers/{importer_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs Route */
        get: operations["runs_route_admin_importers__importer_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/importers/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Types
         * @description All importer types the registry knows about.
         */
        get: operations["list_types_v1_importers_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/importers/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover Route
         * @description Probe the source with provided creds and list available items.
         *
         *     No DB writes — secrets stay in memory only. The wizard sends them
         *     again on save (where they get encrypted).
         */
        post: operations["discover_route_v1_importers_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/importers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Route */
        get: operations["list_route_v1_importers__get"];
        put?: never;
        /** Create Route */
        post: operations["create_route_v1_importers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/importers/{importer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route */
        get: operations["get_route_v1_importers__importer_id__get"];
        put?: never;
        post?: never;
        /** Delete Route */
        delete: operations["delete_route_v1_importers__importer_id__delete"];
        options?: never;
        head?: never;
        /** Update Route */
        patch: operations["update_route_v1_importers__importer_id__patch"];
        trace?: never;
    };
    "/v1/importers/{importer_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Route
         * @description Kick off a run in the background. Returns immediately with the
         *     importer id; poll `/{id}/runs` for the actual run row's progress.
         *
         *     We instantiate the importer up-front (without running it) so a
         *     missing optional-dep package fails the request with a 422 +
         *     pip-install hint instead of letting the background task swallow
         *     the error into the run row.
         */
        post: operations["run_route_v1_importers__importer_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/importers/{importer_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs Route */
        get: operations["runs_route_v1_importers__importer_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/corpus/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats
         * @description Roll-up counters over the chunks table. Cheap — one indexed scan.
         */
        get: operations["stats_v1_corpus_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/corpus/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources
         * @description Per-source roll-up. `order=chunks` ranks by chunk count
         *     (largest sources first); `order=recent` by most recent ingest.
         */
        get: operations["sources_v1_corpus_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_v1_webhooks__get"];
        put?: never;
        /** Create */
        post: operations["create_v1_webhooks__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_v1_webhooks__webhook_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_v1_webhooks__webhook_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_v1_webhooks__webhook_id__patch"];
        trace?: never;
    };
    "/v1/webhooks/{webhook_id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deliveries */
        get: operations["deliveries_v1_webhooks__webhook_id__deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{webhook_id}/deliveries/{delivery_id}/redeliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeliver
         * @description Reset a delivery row to `pending` + next_attempt_at=NOW. The
         *     worker picks it up on the next tick.
         */
        post: operations["redeliver_v1_webhooks__webhook_id__deliveries__delivery_id__redeliver_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{webhook_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test
         * @description Enqueue a synthetic `ping` event for this webhook only.
         *
         *     Useful for first-time setup — verifies URL + signing + receiver
         *     parsing without waiting for a real importer run.
         */
        post: operations["test_v1_webhooks__webhook_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CorpusSource */
        CorpusSource: {
            /** Source */
            source: string;
            /** Chunk Count */
            chunk_count: number;
            /** Recipes */
            recipes: string[];
            /** Last Ingest At */
            last_ingest_at: string | null;
        };
        /** CorpusStats */
        CorpusStats: {
            /** Total Chunks */
            total_chunks: number;
            /** Total Sources */
            total_sources: number;
            /** Total Recipes */
            total_recipes: number;
            /** Chunks With Summary */
            chunks_with_summary: number;
            /** Chunks With Embedding */
            chunks_with_embedding: number;
            /** Last Ingest At */
            last_ingest_at: string | null;
        };
        /** DeliveryOut */
        DeliveryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Webhook Id
             * Format: uuid
             */
            webhook_id: string;
            /** Event */
            event: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /**
             * Next Attempt At
             * Format: date-time
             */
            next_attempt_at: string;
            /** Last Status */
            last_status: number | null;
            /** Last Error */
            last_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Delivered At */
            delivered_at: string | null;
        };
        /** DiscoverIn */
        DiscoverIn: {
            /** Type */
            type: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Secrets */
            secrets?: {
                [key: string]: string;
            };
        };
        /** DiscoverOut */
        DiscoverOut: {
            /** Items */
            items: components["schemas"]["DiscoveredItemOut"][];
        };
        /** DiscoveredItemOut */
        DiscoveredItemOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Hint */
            hint: string | null;
            /** Config Patch */
            config_patch: {
                [key: string]: unknown;
            };
        };
        /**
         * EntityResponse
         * @description One entity returned by ``/fetch_entity``.
         */
        EntityResponse: {
            /** Node Id */
            node_id: string;
            /** Name */
            name: string;
            /** Summary */
            summary: string;
            /** Labels */
            labels?: string[];
            /** Attributes */
            attributes?: {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImporterCreate */
        ImporterCreate: {
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Recipe */
            recipe: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Secrets */
            secrets?: {
                [key: string]: string;
            };
        };
        /** ImporterOut */
        ImporterOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Recipe */
            recipe: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Has Secrets */
            has_secrets: boolean;
            /** Enabled */
            enabled: boolean;
            /** Status */
            status: string;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ImporterTypeOut */
        ImporterTypeOut: {
            /** Type */
            type: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Config Schema */
            config_schema: {
                [key: string]: unknown;
            };
            /** Secret Keys */
            secret_keys: string[];
            /** Supports Discovery */
            supports_discovery: boolean;
            /** Discovery Required */
            discovery_required: string[];
        };
        /** ImporterUpdate */
        ImporterUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Recipe */
            recipe?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Secrets */
            secrets?: {
                [key: string]: string;
            } | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** Proposal */
        Proposal: {
            /**
             * Type
             * @enum {string}
             */
            type: "add" | "correct" | "deprecate";
            /**
             * Target Node Id
             * @description For 'correct'/'deprecate' — node being changed.
             */
            target_node_id?: string | null;
            /**
             * Content
             * @description The proposed fact or correction, in natural language.
             */
            content: string;
            /**
             * Evidence
             * @description Sources backing the claim — URLs, logs, version refs.
             */
            evidence?: string[];
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Submitted By
             * @description Free-form attribution tag — stored verbatim, never trusted.
             * @default anonymous
             */
            submitted_by: string;
        };
        /** ProposalReceipt */
        ProposalReceipt: {
            /** Proposal Id */
            proposal_id: string;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "evaluating" | "accepted" | "rejected" | "escalated" | "errored";
        };
        /** ProposalState */
        ProposalState: {
            /** Proposal Id */
            proposal_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "evaluating" | "accepted" | "rejected" | "escalated" | "errored";
            /**
             * Type
             * @enum {string}
             */
            type: "add" | "correct" | "deprecate";
            /** Content */
            content: string;
            /** Submitted At */
            submitted_at: string;
            /** Submitted By */
            submitted_by: string;
            /** Target Node Id */
            target_node_id?: string | null;
            /** Evidence */
            evidence?: string[];
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Decision At */
            decision_at?: string | null;
            /** Reason */
            reason?: string | null;
            /** Episode Uuid */
            episode_uuid?: string | null;
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Importer Id
             * Format: uuid
             */
            importer_id: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Items Total */
            items_total: number | null;
            /** Items Done */
            items_done: number;
            /** Chunks Added */
            chunks_added: number;
            /** Error Text */
            error_text: string | null;
            /** Triggered By */
            triggered_by: string | null;
        };
        /** RunQueuedOut */
        RunQueuedOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Importer Id
             * Format: uuid
             */
            importer_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /**
         * SearchHit
         * @description One fact returned by ``/search``.
         *
         *     A fact is a graph edge — a one-line statement relating two entities
         *     (``source_node_id`` and ``target_node_id``) extracted from a source
         *     chunk (``episode_ids``). Clients that want more context either
         *     drill into an entity via ``/fetch_entity`` or — usually preferred —
         *     pull the original paragraph via ``/fetch_source``.
         */
        SearchHit: {
            /** Node Id */
            node_id: string;
            /** Summary */
            summary: string;
            /** Source */
            source?: string | null;
            /** Source Node Id */
            source_node_id?: string | null;
            /** Target Node Id */
            target_node_id?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid Until */
            valid_until?: string | null;
            /** Episode Ids */
            episode_ids?: string[];
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
        };
        /**
         * SourceResponse
         * @description One source chunk returned by ``/fetch_source``.
         */
        SourceResponse: {
            /** Episode Id */
            episode_id: string;
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Content */
            content: string;
            /** Created At */
            created_at?: string | null;
            /** Valid At */
            valid_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebhookCreate */
        WebhookCreate: {
            /** Url */
            url: string;
            /** Events */
            events?: string[];
            /** Description */
            description?: string | null;
            /** Secret */
            secret?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** WebhookCreated */
        WebhookCreated: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            /** Events */
            events: string[];
            /** Enabled */
            enabled: boolean;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Delivery At */
            last_delivery_at: string | null;
            /** Last Status */
            last_status: number | null;
            /** Last Error */
            last_error: string | null;
            /** Secret */
            secret: string;
        };
        /** WebhookOut */
        WebhookOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            /** Events */
            events: string[];
            /** Enabled */
            enabled: boolean;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Delivery At */
            last_delivery_at: string | null;
            /** Last Status */
            last_status: number | null;
            /** Last Error */
            last_error: string | null;
        };
        /** WebhookUpdate */
        WebhookUpdate: {
            /** Url */
            url?: string | null;
            /** Events */
            events?: string[] | null;
            /** Description */
            description?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /**
             * Rotate Secret
             * @default false
             */
            rotate_secret: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query: {
                /** @description Natural-language query */
                q: string;
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_entity_v1_fetch_entity__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_source_v1_fetch_source__episode_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_v1_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Proposal"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_v1_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_types_admin_importers_types_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImporterTypeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_route_admin_importers_discover_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_route_admin_importers__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImporterOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_route_admin_importers__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImporterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImporterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_route_admin_importers__importer_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                importer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImporterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_route_admin_importers__importer_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                importer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_route_admin_importers__importer_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                importer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImporterUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImporterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_route_admin_importers__importer_id__run_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                importer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunQueuedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_route_admin_importers__importer_id__runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                importer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_types_v1_importers_types_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImporterTypeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_route_v1_importers_discover_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_route_v1_importers__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImporterOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_route_v1_importers__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImporterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImporterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_route_v1_importers__importer_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                importer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImporterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_route_v1_importers__importer_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                importer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_route_v1_importers__importer_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                importer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImporterUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImporterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_route_v1_importers__importer_id__run_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                importer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunQueuedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_route_v1_importers__importer_id__runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                importer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_v1_corpus_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusStats"];
                };
            };
        };
    };
    sources_v1_corpus_sources_get: {
        parameters: {
            query?: {
                limit?: number;
                order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusSource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_v1_webhooks__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookOut"][];
                };
            };
        };
    };
    create_v1_webhooks__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_v1_webhooks__webhook_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_v1_webhooks__webhook_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_v1_webhooks__webhook_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookOut"] | components["schemas"]["WebhookCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deliveries_v1_webhooks__webhook_id__deliveries_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeliver_v1_webhooks__webhook_id__deliveries__delivery_id__redeliver_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
                delivery_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_v1_webhooks__webhook_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
