{{- if and (not .Values.postgres.existingSecret) .Values.postgres.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse.pgSecretName" . }}
  labels: {{- include "lighthouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  LIGHTHOUSE_PG_URL: {{ .Values.postgres.url | quote }}
{{- end }}
