"""Systematic coverage-gap finder.

Reads `data/source-research/popularity-index.yaml` — a hand-curated
list of "should-have" libraries with their expected chunks.source
match patterns and the source-snippet to add when missing — and
checks each entry against the live corpus.

Output: `data/source-research/coverage-report.md` with one row per
library: ✅ / 🟡 / ❌. Plus an "add me" snippets block so the
corresponding role-recipe yaml can be updated in one paste.

Usage:
    LIGHTHOUSE_PG_URL=postgres://...
    uv run python tools/find_gaps.py
"""

from __future__ import annotations

import asyncio
import logging
import os
import sys
from pathlib import Path

import asyncpg
import yaml

logger = logging.getLogger("find_gaps")
logging.basicConfig(level=logging.INFO, format="%(message)s")

INDEX = Path("data/source-research/popularity-index.yaml")
OUT = Path("data/source-research/coverage-report.md")


async def main() -> int:
    if not INDEX.exists():
        logger.error("popularity index missing at %s", INDEX)
        return 1
    with INDEX.open(encoding="utf-8") as f:
        idx = yaml.safe_load(f)
    libs = idx.get("libraries", [])
    if not libs:
        logger.error("no libraries in %s", INDEX)
        return 1

    dsn = os.environ.get("LIGHTHOUSE_PG_URL") or os.environ.get(
        "LIGHTHOUSE_DATABASE_URL"
    )
    if not dsn:
        logger.error("LIGHTHOUSE_PG_URL env var required")
        return 1

    conn = await asyncpg.connect(dsn)

    rows: list[dict] = []
    for lib in libs:
        patterns = lib.get("match") or []
        chunks = 0
        sources_seen: set[str] = set()
        for p in patterns:
            r = await conn.fetch(
                "SELECT source, COUNT(*) AS n FROM chunks "
                "WHERE source ILIKE '%' || $1 || '%' GROUP BY source",
                p,
            )
            for rec in r:
                if rec["source"] in sources_seen:
                    continue
                sources_seen.add(rec["source"])
                chunks += int(rec["n"])
        min_ok = int(lib.get("expected_chunks_min") or 1)
        status = (
            "covered" if chunks >= min_ok
            else "thin" if chunks > 0
            else "missing"
        )
        rows.append({
            "name": lib["name"],
            "role": lib.get("role", ""),
            "tier": lib.get("tier", "?"),
            "chunks": chunks,
            "sources": len(sources_seen),
            "expected_min": min_ok,
            "status": status,
            "source": lib.get("source"),
        })
    await conn.close()

    # Build markdown report.
    rows_sorted = sorted(rows, key=lambda r: (r["tier"], r["name"]))
    counts = {"covered": 0, "thin": 0, "missing": 0}
    for r in rows_sorted:
        counts[r["status"]] += 1

    out_lines: list[str] = []
    out_lines.append("# Library coverage report")
    out_lines.append("")
    out_lines.append(
        f"Auto-generated by `tools/find_gaps.py` from "
        f"`{INDEX}`. Compares hand-curated 'should-have' libraries "
        f"against `chunks.source` substrings."
    )
    out_lines.append("")
    out_lines.append(
        f"**Summary:** ✅ {counts['covered']}  ·  "
        f"🟡 {counts['thin']}  ·  ❌ {counts['missing']}"
    )
    out_lines.append("")

    # By status section.
    for label, sym, key in (
        ("Missing", "❌", "missing"),
        ("Thin", "🟡", "thin"),
        ("Covered", "✅", "covered"),
    ):
        bucket = [r for r in rows_sorted if r["status"] == key]
        if not bucket:
            continue
        out_lines.append(f"## {sym} {label} ({len(bucket)})")
        out_lines.append("")
        out_lines.append("| Lib | Role | Tier | Chunks | Expected min | Recipe-snippet |")
        out_lines.append("|---|---|---:|---:|---:|---|")
        for r in bucket:
            snippet_flag = (
                "_(no add)_" if not r["source"]
                else f"see `{r['source'].get('name', '')}`"
            )
            out_lines.append(
                f"| **{r['name']}** | `{r['role']}` | T{r['tier']} | "
                f"{r['chunks']} ({r['sources']}) | {r['expected_min']} | "
                f"{snippet_flag} |"
            )
        out_lines.append("")

    # Snippets block — only for missing/thin libs that have a
    # ``source`` entry. Grouped by role so the operator can paste
    # each block into the matching role-recipe yaml in one go.
    by_role: dict[str, list[dict]] = {}
    for r in rows_sorted:
        if r["status"] == "covered":
            continue
        if not r["source"]:
            continue
        by_role.setdefault(r["role"], []).append(r)
    if by_role:
        out_lines.append("---")
        out_lines.append("")
        out_lines.append("## Recipe-append snippets, grouped by role")
        out_lines.append("")
        out_lines.append(
            "Paste each block at the bottom of the matching "
            "`data/source-research/role-recipes/<role>.yaml` under "
            "its appropriate tier section (most additions belong in "
            "tier1_mainstream or tier3_methodology depending on the "
            "library). Then `uv run python tools/role_recipe_compose.py` "
            "and re-trigger the ingest job for that role."
        )
        out_lines.append("")
        for role, libs_role in sorted(by_role.items()):
            out_lines.append(f"### `role-recipes/{role}.yaml`")
            out_lines.append("")
            out_lines.append("```yaml")
            for r in libs_role:
                snip = {**r["source"]}
                out_lines.append(yaml.safe_dump(
                    [snip], sort_keys=False, default_flow_style=False, indent=2
                ).rstrip())
            out_lines.append("```")
            out_lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    logger.info(
        "wrote %s — covered=%d thin=%d missing=%d",
        OUT, counts["covered"], counts["thin"], counts["missing"],
    )
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
