"""Compile role-recipe yamls into runner-consumable source lists.

Each recipe in ``data/source-research/role-recipes/<role>.yaml`` has
four tiers (mainstream / canonical / methodology / streams). The
compiler walks every recipe, flattens the tiers into a single
``sources:`` list per role, and emits:

- ``data/source-research/compiled/<role>.yaml`` — the runner-ready
  spec. ``schedule`` is auto-injected by tier: tier 4 (streams) gets
  ``7d``, tiers 1-3 get ``30d`` or ``60d`` depending on size.

- ``docs/coverage-vs-context7.md`` — a parity matrix per role
  showing which Tier 1 sources we share with Context7 and which we
  don't. Hand-written ``context7_id`` flags drive the matrix.

- ``docs/coverage-differentiators.md`` — what only we have
  (Tiers 2-4), grouped by role.

Run:

    uv run python tools/role_recipe_compose.py

Idempotent. Safe to re-run on any recipe edit.
"""

from __future__ import annotations

import logging
from collections.abc import Iterable
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)


RECIPE_DIR = Path("data/source-research/role-recipes")
COMPILED_DIR = Path("data/source-research/compiled")
PARITY_MD = Path("docs/coverage-vs-context7.md")
DIFF_MD = Path("docs/coverage-differentiators.md")


TIER_ORDER = (
    "tier1_mainstream",
    "tier2_canonical",
    "tier3_methodology",
    "tier4_streams",
)


def _default_schedule(tier: str, source: dict) -> str:
    """Pick a cadence based on tier and connector.

    Tier 4 streams need frequent polling. RFCs/standards are stable
    — quarterly. Doc sites are middle ground."""
    if tier == "tier4_streams":
        connector = source.get("connector", "")
        return "1d" if connector == "rss" else "7d"
    if tier == "tier2_canonical":
        return "60d"
    return "30d"


def _flatten_recipe(recipe: dict) -> list[dict]:
    """Walk every tier in a recipe and yield runner-shaped source
    dicts. ``tier`` and ``rationale`` are kept in metadata for
    audit-time inspection but stripped before the runner sees them."""
    out: list[dict] = []
    for tier in TIER_ORDER:
        for src in recipe.get(tier) or []:
            spec = {
                "name": src["id"],
                "connector": src["connector"],
                "args": src.get("args", {}),
                "schedule": {"every": _default_schedule(tier, src)},
            }
            out.append(spec)
    return out


def _gather_recipes() -> Iterable[tuple[str, dict, Path]]:
    if not RECIPE_DIR.exists():
        logger.warning("no recipes dir at %s — nothing to compile", RECIPE_DIR)
        return
    for path in sorted(RECIPE_DIR.glob("*.yaml")):
        with path.open(encoding="utf-8") as f:
            recipe = yaml.safe_load(f) or {}
        role = recipe.get("role") or path.stem
        yield role, recipe, path


def _write_compiled(role: str, sources: list[dict]) -> Path:
    COMPILED_DIR.mkdir(parents=True, exist_ok=True)
    out = COMPILED_DIR / f"{role}.yaml"
    payload = {"sources": sources}
    with out.open("w", encoding="utf-8") as f:
        f.write(
            "# Auto-generated by tools/role_recipe_compose.py.\n"
            f"# Source: data/source-research/role-recipes/{role}.yaml\n"
            "# Do not edit directly — edit the recipe instead.\n\n"
        )
        yaml.safe_dump(
            payload, f, sort_keys=False, default_flow_style=False, indent=2
        )
    return out


def _render_parity_md(rows: list[tuple[str, dict]]) -> str:
    out: list[str] = []
    out.append("# Tier 1 parity with Context7")
    out.append("")
    out.append(
        "Auto-generated by `tools/role_recipe_compose.py`. Per-role view "
        "of mainstream sources, flagged where Context7 has an overlap. "
        "A `parity: critical` source we lack vs Context7 is a gap to "
        "close; a Tier 2-4 source we have that Context7 doesn't is our "
        "differentiator."
    )
    out.append("")
    for role, recipe in rows:
        out.append(f"## {role}")
        out.append("")
        out.append(
            f"Audit domains: {', '.join(recipe.get('audit_domains', []))}"
        )
        out.append("")
        out.append("| Source | Context7 id | Parity | Rationale |")
        out.append("|---|---|---|---|")
        for src in recipe.get("tier1_mainstream") or []:
            c7 = src.get("context7_id", "—")
            par = src.get("parity", "—")
            rat = (src.get("rationale", "") or "").replace("\n", " ")[:80]
            out.append(f"| `{src['id']}` | `{c7}` | {par} | {rat} |")
        out.append("")
    return "\n".join(out) + "\n"


def _render_differentiators_md(rows: list[tuple[str, dict]]) -> str:
    out: list[str] = []
    out.append("# Lighthouse differentiators vs Context7")
    out.append("")
    out.append(
        "Auto-generated. Lists Tier 2 (canonical standards), Tier 3 "
        "(practitioner content) and Tier 4 (streaming) sources per "
        "role. Context7 has zero coverage of these by design — they "
        "ship framework docs, not the literature about using them well."
    )
    out.append("")
    for role, recipe in rows:
        out.append(f"## {role}")
        out.append("")
        for tier, label in [
            ("tier2_canonical", "Canonical standards"),
            ("tier3_methodology", "Methodology / practice"),
            ("tier4_streams", "Streaming / time-aware"),
        ]:
            srcs = recipe.get(tier) or []
            if not srcs:
                continue
            out.append(f"### {label}")
            out.append("")
            for src in srcs:
                rat = (src.get("rationale", "") or "").replace("\n", " ")
                out.append(f"- `{src['id']}` — {rat}")
            out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s | %(message)s",
    )
    compiled = 0
    parity_rows: list[tuple[str, dict]] = []
    for role, recipe, path in _gather_recipes():
        sources = _flatten_recipe(recipe)
        if not sources:
            logger.warning("recipe %s has no sources — skipping", path)
            continue
        out = _write_compiled(role, sources)
        logger.info(
            "compiled %s -> %s (%d sources across %d tiers)",
            path.name,
            out,
            len(sources),
            sum(1 for t in TIER_ORDER if recipe.get(t)),
        )
        compiled += 1
        parity_rows.append((role, recipe))

    if parity_rows:
        PARITY_MD.parent.mkdir(parents=True, exist_ok=True)
        PARITY_MD.write_text(_render_parity_md(parity_rows), encoding="utf-8")
        DIFF_MD.write_text(
            _render_differentiators_md(parity_rows), encoding="utf-8"
        )
        logger.info("wrote %s and %s", PARITY_MD, DIFF_MD)

    if not compiled:
        logger.warning("no recipes compiled")
        return 1
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
